#!/bin/bash

trap cleanup 0 1 2 3 15

cleanup()
{
	rm -rf /tmp/wl3
	exit 0
}

if [[ $0 == ./C-interp ]] || [[ $0 == C-interp ]]; then
	if [[ "$#" -ne 1 ]]; then
		echo "C-interp only accepts 1 argument."
		exit 1
	fi

	CINT_PATH=$(realpath $0)
	FILE=$(echo $1 | cut -f1 -d.)
	ln -s $CINT_PATH $FILE 2>/dev/null
	if [[ "$?" -eq 0 ]]; then
		echo Sym Link to C-interp \"$FILE\" created.
	else
		echo Failed to create link \"$FILE\"\; it already exists.
		exit 1
	fi
else
	# Create /tmp/wl3 if it does not exist
	mkdir -p /tmp/wl3

	CFILE=$0
	CFILE+=".c"
	BASENAME=$(basename $0)
	EXEC_DEST="/tmp/wl3/"
	EXEC_DEST+=$BASENAME

	gcc -std=c99 $CFILE -o $EXEC_DEST
	$EXEC_DEST $@

fi
