#!/bin/bash 

# Checks if trashbin exists
if [[ -d "~/trashbin" ]]; then
	echo "Error: Trashbin does not exist. Please call 'srm' first before calling any other 'rm' functions."
	exit 1
fi

# Checks if trashbin is empty
if [[ -z "~/trashbin/trash_content" ]]; then
	echo "Error: Trashbin is empty."
	exit 1
fi

# Clears the trash_content and the log
rm -rf ~/trashbin/trash_content/*
rm -f ~/trashbin/trashlog
touch ~/trashbin/trashlog
